### ISSUE TITLE
Failed to connect to Ubuntu 22 instance

### ISSUE THREAD

**Issue by Narzhan** [exoscale/terraform-provider-exoscale#179]
I've a Terraform script which starts up several VMs with different OSes and runs some tests on them. These tests work fine on Ubuntu 20, Debian 10 and 11, Centos and many others. However with the release of Ubuntu 22 I'm not able to connect to the vm using ssh with the following error.

` ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

The sample configuration to reproduce the problem:

```
variable "exoscale_api_key" {
  type = string
}
variable "exoscale_api_secret" {
  type = string
}
variable "public_key" {
  type = string
}

terraform {
  required_providers {
    exoscale = {
      source = "exoscale/exoscale"
      version = "0.35"
    }
  }
}

provider "exoscale" {
  key = var.exoscale_api_key
  secret = var.exoscale_api_secret
}

locals {
  zone = "ch-dk-2"
  size = "Micro"
  disk_size = 10
  security_groups = [
    "group"]
}


resource "exoscale_ssh_keypair" "key" {
  name = "vm-test"
  public_key = var.public_key
}

data "exoscale_compute_template" "ubuntu_22" {
  zone = local.zone
  name = "Linux Ubuntu 22.04 LTS 64-bit"
}



resource "exoscale_compute" "vm_ubuntu_22" {
  display_name = "tmp-terraform-test-u22"
  template_id = data.exoscale_compute_template.ubuntu_22.id
  size = local.size
  key_pair = exoscale_ssh_keypair.key.name
  disk_size = local.disk_size
  zone = local.zone
  security_groups = local.security_groups

  connection {
    type = "ssh"
    host = self.ip_address
    user = self.username
    private_key = file("key")
  }


  provisioner "remote-exec" {
    inline = [
      "sleep 20",
      "echo test",
    ]
  }

}
```

**Comment by llambiel** [comment]
Thanks @Narzhan for the report

Ubuntu 22.04 features OpenSSH version 8.9. Starting version 8.8 ssh-rsa (SHA1) key support has been [deprecated](https://www.linuxadictos.com/en/openssh-8-8-arrives-saying-goodbye-to-ssh-rsa-support-bug-fixes-and-more.html). Our system currently generates SHA1 keys, which prevent you to connect.

We'll look at generating proper SHA-512 keys

**Comment by PhilippeChepy** [comment]
Hello @Narzhan,

~~You seem to generate the public key before provisioning it using Terraform. As @llambiel mentioned, `ssh-rsa` (SHA1 signature scheme) is not supported anymore in Ubuntu 22.04 because of a more recent version of OpenSSH which deprecate this kind of keys. To work around this limitation, you should change the value of your `public_key` input variable to a `rsa-sha2-256` or `rsa-sha2-512` key type.~~

~~Another quick and (a bit) dirty workaround is to use `replace(var.public_key, "ssh-rsa", "rsa-sha2-256")` instead of `var.public_key` in your `exoscale_ssh_keypair` resource defintion. Replacing the signature type should be sufficient to get compatibility back, because [according to RFC8332, page 3](https://www.ietf.org/rfc/rfc8332.txt), speaking about `rsa-sha2-256` and 512 keys:~~

> ~~All aspects of the "ssh-rsa" format are kept, including the encoded string "ssh-rsa".  This allows existing RSA keys to be used with the new public key algorithms, without requiring re-encoding or affecting already trusted key fingerprints.~~

NOTE: The [`exoscale_ssh_keypair`](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/ssh_keypair) resource is deprecated and has been replaced by the [`exoscale_ssh_key`](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/ssh_key) resource. You can easily swap them in your configuration.

EDIT: after some tests, it looks like the limitation is on the Terraform ssh provisioner side: while terraform is continuously trying to connect to the instance, I'm perfectly able to connect the same instance using the same ssh key as specified in the TF configuration. The `ssh-rsa` key type allows auto-negotiation of the sha2 signature algorithm when using the OpenSSH client, while Terraform's remote provisioner seems to be not able to do so. This issue is not provider-specific and should be reported upstream in the Terraform bug tracker. In the meantime, a quick workaround is to use an `ED25519` key instead.

**Comment by exo-cedric** [comment]
Recent versions of Terraform should fix this issue (as of https://github.com/hashicorp/terraform/pull/30962)

**Comment by PhilippeChepy** [comment]
Update 2:
@Narzhan, can you try with Terraform 1.2.3 (current latest version)?
It looks like HCP has fixed this issue ([see here](https://github.com/hashicorp/terraform/pull/30962))

With the latest version, your snippet works like a charm.

**Comment by Narzhan** [comment]
Hi, it seems like everything is ok.

**Comment by PhilippeChepy** [comment]
Thank you for your feedback.

I'm closing this issue.
