### ISSUE TITLE
State locking with Exoscale SOS / S3

### ISSUE THREAD

**Issue by rubij** [exoscale/terraform-provider-exoscale#19]
Hello,

I am wondering if it is possible to enable state locking using the SOS resource ? (and so a DynamoDB ?)

Best regards
Jonathan Rubiero

**Comment by falzm** [comment]
Hi @rubij, if I understand what you try to achieve correctly (using the `s3` backend to store your TF remote state on Exoscale SOS and use an AWS DynamoDB table for locking), that won't work since you'd set Exoscale API credentials in the backend configuration and those would be reused to authenticate against the AWS API for DynamoDB...

**Comment by rubij** [comment]
Hi @falzm, thanks for your reply, we can close this issue.
