### ISSUE TITLE
Best practice to provision a compute instance with Terraform

### ISSUE THREAD

**Issue by wasadigi** [exoscale/terraform-provider-exoscale#192]
Hello,

This is not an issue, but rather a question on the recommended way to provision compute instances with Terraform. I would like to confirm my understanding of the situation, and ask for feedback on how people are addressing this topic.

* The Terraform resources have changed (`exoscale_compute` replaced by `exoscale_compute_instance`, `exoscale_ssh_keypair` replaced by `exoscale_ssh_key`). 

* My understanding is that in the past, it was possible to let the compute instance generate a password (for an instance) and a private key (for a keypair), if these values were not provided. This was a way to bootstrap the process: I can ask Exoscale to create the resource, initialize the credentials, give them back to me and proceed. 

* Today, this is not possible anymore: to create a compute instance, I have to give the name of a public key that I have imported in Exoscale. Before that, I have to create a key pair *outside* Exoscale and to import the public key.

* Using the [`tls_private_key`](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key) resource would be a way to do it. But for security reasons, Terraform does not recommend it (the public and private keys are stored in the statefile).

* I have played around with `local-exec` provisioner and it kind of works, but I anticipate issues when I run `terraform apply` in the cicd pipeline (local file won't be there anymore).

Does that make sense? Any recommendation or examples that I could look at?

Many thanks for any idea :-)

**Comment by PhilippeChepy** [comment]
Hello @wasadigi,

I will try to answer all the points you raised:

1. For provisioning an instance, the ideal terraform resource is now `exoscale_compute_instance`. Since we are migrating the provider from our legacy API to the OpenAPI v2 flavor, `exoscale_compute` and `exoscale_ssh_keypair` were deprecated, in favor of respectively `exoscale_compute_instance` and `exoscale_ssh_key`.

2. The instance password is available in the deprecated `exoscale_compute` resources but not in the new `exoscale_compute_instance` (the new API doesn't allow to retrieve it). The new `exoscale_ssh_key` resource is also not generating a private key because we were way more reluctant to store secrets in the Terraform state in the past.

3. You are right, it's not possible with not-deprecated Exoscale resources, but you can use the `tls_private_key` resource, as you mentioned:
```terraform
resource "tls_private_key" "admin_key" {
  algorithm   = "ED25519"
}

resource "exoscale_ssh_key" "admin_key" {
  name       = "my-admin-key"
  public_key = tls_private_key.admin_key.public_key_openssh
}
```

4. Hashicorp doesn't recommend using `tls_private_key` in production, for security reasons: "Use of this resource for production deployments is not recommended." In fact, the deprecated `exoscale_ssh_keypair` resource also falls into this situation, and that's why it was deprecated in the first place: it stores the private key in the terraform state. Is this bad? There is no universal answer to this question, but I would rather say "it depends" (What are your organizational needs ? Where and how the state is stored ? etc.). If the state is encrypted at rest AND in transit (TLS), this could potentially be OK to use this resource. You also would probably take a look at what Hashicorp says in their documentation:
  - [Sensitive Data in State: Recommendations](https://www.terraform.io/language/state/sensitive-data#recommendations).
  - More for provider developers, but good to know: [Handling Sensitive Values in State: Don't Encrypt State](https://www.terraform.io/plugin/sdkv2/best-practices/sensitive-state#don-t-encrypt-state).

5. `local-exec` is often more a hack than something else. Sometimes it can make miracles :)

**Comment by wasadigi** [comment]
Hi @PhilippeChepy, thank you very much for your explanations.

This confirms my understanding. I am now thinking about writing an "out-of-terraform" procedure to initialize the process (generate the keypair, create the public key with `exo`). We are using Vault, so once this is configured, I can get rid of the authorized_key.
