### ISSUE TITLE
SKS Load Balancer is not destroyed

### ISSUE THREAD

**Issue by Breee** [exoscale/terraform-provider-exoscale#210]
Greetings, 
given the following cluster

```hcl
terraform {
  required_providers {
    exoscale = {
      source = "exoscale/exoscale"
      version = "0.38.0"
    }
  }
}

provider "exoscale" {
}

locals {
  zone = "de-muc-1"
}

resource "exoscale_sks_cluster" "cluster_demo" {
  zone    = local.zone
  name    = "cluster-demo"
  version = "1.24.2"
  service_level = "starter"
  cni = "calico"
  exoscale_ccm = true
}
```  
-  `terraform apply` will create a SKS cluster.  
-  `exoscale_ccm = true`  will create a Load Balancer if I got it right.   
-  However,  if I execute  `terraform destroy`, the Load Balancer still exists. (And it costs money)  

I think this might  be a bug. 
Also: Do I need the exoscale_ccm to obtain an external  IP? When I set this setting to false the external IP was just  stuck in "pending". 

Kind Regards
Bree

**Comment by PhilippeChepy** [comment]
Hello @Breee,

The cloud controller manager (CCM) is responsible for managing LoadBalancer services in your SKS cluster. That's also why you will have LoadBalancer services waiting for their IP address ("Pending") if you don't deploy the CCM.
If you want LoadBalancer service integration with the Exoscale Network Load Balancer (NLB) product, you don't have any other choice than to deploy the Exoscale CCM.

Terraform is not aware of resources whose life cycle is entirely managed directly by the CCM. Tha'ts why destroying your cluster using Terraform won't destroy the NLB.

If you want to keep the current behavior and release your Load Balancer (NLB), you need to remove the related service from your SKS cluster before destroying it, so the CCM can destroy it from your account. You can of course still remove NLBs manually using the portal or the CLI afterward.

If you want to manage the NLB lifecycle with Terraform instead of the CCM, you can provision them yourself using the [`exoscale_nlb`](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/nlb) resource, and put appropriate annotations on your LoadBalancer service manifest. This latest solution still require the CCM in order to map your service ports to the NLB, but the NLB creation & removal would be handled by Terraform instead of the CCM.

Additional documentation:
- [The Exoscale CCM repository](https://github.com/exoscale/exoscale-cloud-controller-manager/)
- [Kubernetes Services with Exoscale Network Load Balancers](https://github.com/exoscale/exoscale-cloud-controller-manager/blob/master/docs/service-loadbalancer.md)
- [Example LoadBalancer service with annotations](https://github.com/exoscale/exoscale-cloud-controller-manager/blob/master/docs/examples/service-load-balancer.yml)

**Comment by Breee** [comment]
I see, makes sense. If I don't wanna use the CCM/ NLB product, i just have to expose the service I guess. 

Thanks for the information and sorry for the late reply.
