### ISSUE TITLE
Creating IAM access key fails: Cannot generate IAMv2 `Access Key` using a IAMv3 `Api Key`

### ISSUE THREAD

**Issue by bacbos** [exoscale/terraform-provider-exoscale#290]
I'm trying to create an access key but the provider seems to lack behind on the recently refactored IAM.

Creating the resource fails with the message:

> invalid request: Cannot generate IAMv2 `Access Key` using a IAMv3 `Api Key`

This is my configuration:

```
resource "exoscale_iam_access_key" "my-bucket" {
  name       = "my-bucket"
  operations = [
    "get-sos-object",
   ...
  ]
  resources  = ["sos/bucket:my-bucket"]

```

Is there any known workaround that I could use until the provider is updated?

**Comment by sauterp** [comment]
Hi,

the reason we can't let users create a legacy key(IAMv2) with a non-legacy key(IAMv3) and vice versa, is because when a key is created with another key, we need to check that the key being created only has a subset of the permissions of the creating key. Since legacy and non-legacy keys have incompatible specifications, it's impossible to do this check correctly. Hence we don't allow it.

That said, you are correct, the terraform provider does not yet support IAMv3. We are working on it though.

Until we get there the only 'workaround' I can suggest is to only use legacy keys when working with the terraform provider.

**Comment by bacbos** [comment]
Thanks @sauterp , that makes absolute sense. I was unsure if I'm doing something wrong but in this case I'll follow the upcoming releases for changes concerning IAM.

Thanks!
