### ISSUE TITLE
Setting SSH keys on compute instance is broken

### ISSUE THREAD

**Issue by nuschk** [exoscale/terraform-provider-exoscale#69]
Consider this hcl:

```hcl

provider "exoscale" {
    token = "${var.exoscale_api_key}"
    secret = "${var.exoscale_secret_key}"
}

resource "exoscale_ssh_keypair" "ssh-access" {
  name = "ssh-access"
  public_key = "ssh-rsa AA<snip>"
}

resource "exoscale_compute" "node" {
    display_name = "node-${count.index}"
    zone = "ch-dk-2"
    template = "Linux CoreOS 1576 64-bit"
    size = "Micro"
    disk_size = 10
    key_pair = "${exoscale_ssh_keypair.ssh-access.id}"
    state = "Running"
    security_groups = ["default"]

    user_data = "${file("cloud-config.yml")}"
}
```

Applying will result in defaultKey being set on the instance, although terraform reports success. On each apply, it's trying to set again.

**Comment by greut** [comment]
@nuschk sadly this is a bug that cannot be resolved in the terraform provider. If two SSH keys have the same _fingerprint_, the API answers with one of name. And in this case, not the one you expecting. In the portal, you'all also see the other ssh keypair displayed.

The workaround is to ignore changes on the `key_pair`, which is fine since changing it via the API (what Terraform does), doesn't have any effect on the machines as this is provisioned only during the first boot by _cloud-init_.

```hcl
resource "exoscale_compute" "node" {
  ...

  lifecycle {
    ignore_changes = ["key_pair"]
  }
}
```

ping @marcaurele 

ps: if you don't get any answer here, drop us a line via the support channel in the Portal.

**Comment by nuschk** [comment]
Ah, that explains it, thank you. Obviously, I wouldn't want the two key pairs to be the same in a production setup, so no problem for me. Thanks!
